# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tanyunxi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tanyunxi(object):
    def setupUi(self, Tanyunxi):
        Tanyunxi.setObjectName("Tanyunxi")
        Tanyunxi.resize(899, 570)
        self.centralWidget = QtWidgets.QWidget(Tanyunxi)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(400, 50, 121, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 741, 431))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.comboBox4 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox4.setGeometry(QtCore.QRect(320, 60, 69, 22))
        self.comboBox4.setObjectName("comboBox4")
        self.comboBox4.addItem("")
        self.comboBox4.addItem("")
        self.comboBox4.addItem("")
        self.comboBox4.addItem("")
        Tanyunxi.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(Tanyunxi)
        self.statusBar.setObjectName("statusBar")
        Tanyunxi.setStatusBar(self.statusBar)

        self.retranslateUi(Tanyunxi)
        QtCore.QMetaObject.connectSlotsByName(Tanyunxi)

    def retranslateUi(self, Tanyunxi):
        _translate = QtCore.QCoreApplication.translate
        Tanyunxi.setWindowTitle(_translate("Tanyunxi", "Tanyunxi"))
        self.label.setText(_translate("Tanyunxi", "24小时空气质量(AQI)"))
        self.comboBox4.setItemText(0, _translate("Tanyunxi", "广州"))
        self.comboBox4.setItemText(1, _translate("Tanyunxi", "北京"))
        self.comboBox4.setItemText(2, _translate("Tanyunxi", "上海"))
        self.comboBox4.setItemText(3, _translate("Tanyunxi", "成都"))
